### ISSUE TITLE
застосування валідаторів

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-58-MongoBD-ODM-Mongoose#1]
https://github.com/BohdanLuts/home-work-lesson-58-MongoBD-ODM-Mongoose/blob/4f0c13484f3096337b121dab64194524fd186035/controller/phone.controller.js#L60
- тут треба уважно вмикати/вимикати валідатори. Як правило, при оновленні дані мають відповідати тим же обмеженням, що і при створенні, тому зазвичай валідатори при оновленні вмикають.

**Comment by BohdanLuts** [comment]
Валідатори не були розкоментовані після тестування застосунку. Виправлено.
